### PR TITLE
Updated this mod to the new version of spartan weaponry.

### PR DESCRIPTION
**Pull request by Trinsdar**
I removed the libs folder from github as you don't need to upload it to github and having the spartan weaponry jar in this repository breaks the license terms as it's all rights reserved. Also right now the ItemRegistrySBM is throwing errors for the ModelRenderRegistry methods right now.

### CODE REVIEW

**Comment by Trinsdar** [comment]
the mod is now updated to work with the latest version of spartan weaponry.

**Comment by Trinsdar** [comment]
Also by the way I added battleaxes, boomerangs, and maces.
Edit: I also added Parrying daggers, though I unregistered it after I saw that it is a work in progress

**Comment by Trinsdar** [comment]
I just need to add recipes and then it should be done.

**Comment by Trinsdar** [comment]
Ok I think I am completely done now.

**Comment by Trinsdar** [comment]
I reregistered the parrying dagger after I saw that it is only on when experimental features are turned on.

**Comment by Kovak** [comment]
This is some very cool work, i'll get this merged this weekend!

**Pull request merged**
